version: '3.8'

services:
  simple-torrent:
    build:
      context: .
      dockerfile: Dockerfile
    image: simple-torrent:latest
    container_name: simple-torrent
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "50007:50007"
      - "50007:50007/udp"
    environment:
      - AUTH=username:password
      - TITLE=SimpleTorrent
    volumes:
      - ./downloads:/downloads
      - ./torrents:/torrents
