name: Release Build

on:
  push:
    tags:
      - 'v*'
      - '1.*'
  workflow_dispatch:

jobs:
  build:
    name: Build Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Get dependencies
        run: |
          go mod download

      - name: Build Binaries
        run: |
          bash scripts/make_release.sh gzip amd64 purego
          bash scripts/make_release.sh gzip 386 purego
          bash scripts/make_release.sh gzip arm64 purego
          bash scripts/make_release.sh gzip darwin purego

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cloud-torrent_linux_amd64_static.gz
            cloud-torrent_linux_386_static.gz
            cloud-torrent_linux_arm64_static.gz
            cloud-torrent_darwin_amd64_static.gz
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
